// ============================================================
// PLANET DATA
// ============================================================
const PLANETS=[
// Segmentum Solar
{id:'terra',name:'Terra',x:268,y:418,type:'throne',founding:'special',
 info:'The Golden Throne. Seat of the Emperor of Mankind and heart of the Imperium. Protected by the Adeptus Custodes and garrisoned by the Imperial Fists.',
 chapter:'Imperial Fists (Garrison)',seg:'Segmentum Solar'},
{id:'chogoris',name:'Chogoris',x:445,y:415,type:'civilized',founding:'first',
 info:'Homeworld of the White Scars Chapter. A world of vast steppes and nomadic warrior tribes. The Great Khan leads lightning-fast crusades across the stars.',
 chapter:'White Scars',seg:'Segmentum Solar'},
{id:'keletros',name:'Keletros',x:305,y:390,type:'fortress',founding:'later',
 info:'Chapter world of the Skull Bearers. A fortress world carved from ancient rock, its citadels guard the approach to the Sol System.',
 chapter:'Skull Bearers',seg:'Segmentum Solar'},
{id:'xenax',name:'Xenax',x:305,y:438,type:'civilized',founding:'later',
 info:'Chapter world of the Subjugators. Known for brutal training regimens that forge warriors of unmatched discipline and siege expertise.',
 chapter:'Subjugators',seg:'Segmentum Solar'},
{id:'felis',name:'Felis',x:358,y:451,type:'civilized',founding:'later',
 info:'Chapter world of the White Panthers. The agri-world produces fierce hunters from its wide plains who become expert infiltrators.',
 chapter:'White Panthers',seg:'Segmentum Solar'},
{id:'eyrie',name:'Eyrie',x:185,y:475,type:'fortress',founding:'later',
 info:'Storm-wracked fortress world of the Storm Wings. Towering spires pierce eternal cloud cover from which the Storm Wings strike without warning.',
 chapter:'Storm Wings',seg:'Segmentum Solar'},
{id:'paragon',name:'Paragon',x:238,y:482,type:'civilized',founding:'later',
 info:'Chapter world of the Emperor\'s Hands. A world of absolute devotion — its entire population serves in support of the Chapter\'s eternal war.',
 chapter:"Emperor's Hands",seg:'Segmentum Solar'},
{id:'bloodfall',name:'Bloodfall',x:220,y:510,type:'desolate',founding:'later',
 info:'Chapter world of the Red Wolves. Named for the crimson waterfalls cascading from iron mountains stained by ancient battles.',
 chapter:'Red Wolves',seg:'Segmentum Solar'},
{id:'pranacar',name:'Pranacar',x:368,y:502,type:'civilized',founding:'later',
 info:'Chapter world of the Sky Sentinels. High-altitude plateaus produce warriors with predatory instincts and exceptional spatial awareness.',
 chapter:'Sky Sentinels',seg:'Segmentum Solar'},
{id:'therock',name:'The Rock',x:400,y:538,type:'fortress',founding:'first',
 info:'The mobile fortress-monastery of the Dark Angels, a fragment of their destroyed homeworld Caliban. Harbors the dark secret of the Fallen Angels within its deepest dungeons.',
 chapter:'Dark Angels',seg:'Segmentum Solar'},
{id:'nocturne',name:'Nocturne',x:440,y:509,type:'volcanic',founding:'first',
 info:'Homeworld of the Salamanders Chapter. A world of volcanic fury and extreme conditions. The Salamanders are renowned for their mastery of flame and extraordinary artificer craftsmanship.',
 chapter:'Salamanders',seg:'Segmentum Solar'},
{id:'ogrys',name:'Ogrys (Ruins)',x:462,y:292,type:'ruins',founding:'later',
 info:'Ruined former chapter world. Once home to the Invaders Chapter, Ogrys was devastated by an unspecified catastrophe. The Invaders are believed entirely lost.',
 chapter:'Invaders (Lost)',seg:'Segmentum Solar'},
{id:'impfists_s',name:'Imperial Fists',x:312,y:493,type:'crusade',founding:'first',
 info:'The Imperial Fists maintain no fixed chapter world. They patrol in their fortress-ship Phalanx throughout the Segmentum Solar. This marks a known patrol corridor.',
 chapter:'Imperial Fists',seg:'Segmentum Solar'},
 
// Eye of Terror Region
{id:'eyeofterror',name:'Eye of Terror',x:212,y:302,type:'warpstorm',founding:'special',
 info:'A vast and terrible Warp rift — a permanent tear in reality through which the Chaos Gods pour forth their daemonic legions. Home to the Traitor Legions since the Horus Heresy ten thousand years ago.',
 chapter:'Chaos Domain',seg:'Segmentum Obscurus'},
{id:'fenris',name:'Fenris',x:378,y:295,type:'ice',founding:'first',
 info:'Death world and homeworld of the Space Wolves Chapter. An ice-locked planet of glaciers and vast seas, home to ferocious predators and the fierce Fenrisian people. The Fang is the mightiest fortress-monastery in the galaxy.',
 chapter:'Space Wolves',seg:'Segmentum Obscurus'},
{id:'baal',name:'Baal',x:533,y:270,type:'desolate',founding:'first',
 info:'Homeworld of the Blood Angels Chapter. A world of irradiated deserts and ancient ruins. The Blood Angels are beloved among all Imperial citizens, yet cursed by the Black Rage that haunts their gene-seed.',
 chapter:'Blood Angels',seg:'Segmentum Obscurus'},
{id:'medusa',name:'Medusa',x:165,y:312,type:'desolate',founding:'first',
 info:'Homeworld of the Iron Hands Chapter. A barren, storm-wracked world constantly reshaped by tectonic upheaval. The Iron Hands replace their own flesh with bionics, despising the weakness of biological form.',
 chapter:'Iron Hands',seg:'Segmentum Obscurus'},
{id:'draconith',name:'Draconith',x:118,y:267,type:'desolate',founding:'later',
 info:'Chapter world of the Star Dragons. A remote world near the Halo Stars, shrouded in mystery. The Star Dragons strike hard and fast, like their namesake, leaving ruin in their wake.',
 chapter:'Star Dragons',seg:'Halo Stars'},
{id:'jaggafall',name:'Jaggafall',x:180,y:202,type:'civilized',founding:'later',
 info:'Chapter world of the Blood Swords. Located in Segmentum Obscurus near the Eye of Terror, the Blood Swords stand constant vigil against Chaos incursions spilling from the warp rift.',
 chapter:'Blood Swords',seg:'Segmentum Obscurus'},
{id:'darkhold',name:'Darkhold',x:145,y:347,type:'desolate',founding:'later',
 info:'Chapter world of the Dark Sons. A world perpetually shrouded in darkness, its sun blocked by vast toxic storm clouds. The Dark Sons have adapted to fighting in near-total blackness.',
 chapter:'Dark Sons',seg:'Segmentum Obscurus'},
{id:'neutra',name:'Neutra',x:195,y:355,type:'civilized',founding:'later',
 info:'Chapter world of the Relictors. A controversial chapter known for their study and use of Chaos artifacts to better understand — and combat — the Ruinous Powers.',
 chapter:'Relictors',seg:'Segmentum Obscurus'},
{id:'ingiga',name:'Ingiga',x:225,y:370,type:'civilized',founding:'later',
 info:'Chapter world of the Angels of Fury. A world of towering mountain ranges and fortress-cities carved into cliff faces. The Angels of Fury are expert siege breakers and mountain warfare specialists.',
 chapter:'Angels of Fury',seg:'Segmentum Obscurus'},
{id:'banish',name:'Banish',x:160,y:390,type:'fortress',founding:'later',
 info:'Chapter world of the Exorcists. Uniquely, candidates are subjected to genuine demonic possession during their trials, then fully exorcised — leaving them with innate resistance to warp corruption.',
 chapter:'Exorcists',seg:'Segmentum Pacificus'},
{id:'sabatine',name:'Sabatine',x:200,y:410,type:'civilized',founding:'later',
 info:'Chapter world of the White Consuls. This chapter is noted for their political acumen and extremely close ties to local Imperial governance structures.',
 chapter:'White Consuls',seg:'Segmentum Pacificus'},
{id:'sanctum',name:'Sanctum',x:162,y:435,type:'fortress',founding:'later',
 info:'Chapter world of the White Templars. Following strict codes of honor and absolute purity, the White Templars carry no heraldry save the Emperor\'s golden aquila on their pristine armor.',
 chapter:'White Templars',seg:'Segmentum Pacificus'},
{id:'black_t',name:'Black Templars',x:124,y:402,type:'crusade',founding:'second',
 info:'The Black Templars maintain no homeworld, prosecuting eternal Crusades across the entire galaxy. They are among the largest Chapters in existence, their numbers far exceeding the Codex limit of one thousand warriors.',
 chapter:'Black Templars',seg:'Multiple Segmenta'},
 
// Segmentum Obscurus
{id:'brycantia',name:'Brycantia',x:148,y:88,type:'ice',founding:'later',
 info:'Chapter world of the Iron Knights. A cold, mineral-rich world near the Halo Stars. The Iron Knights are stoic defenders known for their interlocking shield-wall battle doctrines.',
 chapter:'Iron Knights',seg:'Segmentum Obscurus'},
{id:'silence',name:'Silence',x:190,y:148,type:'desolate',founding:'later',
 info:'Chapter world of the Night Watch. Despite its ominous name, Silence is populated — its people live in strict ritual silence by ancient tradition. The Night Watch prefer covert, unseen operations.',
 chapter:'Night Watch',seg:'Segmentum Obscurus'},
{id:'outrenacht',name:'Outrenacht',x:330,y:158,type:'fortress',founding:'later',
 info:'Chapter world of the Legion of Night. A heavily fortified world guarding key approaches through Segmentum Obscurus. The Legion of Night excel at sabotage and stealth operations.',
 chapter:'Legion of Night',seg:'Segmentum Obscurus'},
{id:'cousteau',name:'Cousteau XI',x:357,y:192,type:'ruins',founding:'later',
 info:'Destroyed former chapter world of the Fire Hawks. Cousteau XI was obliterated by catastrophic warp events. The Fire Hawks themselves are listed as lost — believed merged into the legendary Legion of the Damned.',
 chapter:'Fire Hawks (Lost)',seg:'Segmentum Obscurus'},
{id:'zephyr',name:'Zephyr',x:295,y:267,type:'civilized',founding:'later',
 info:'Chapter world of the Storm Hawks. A world of perpetual electrical storms and raging winds. The Storm Hawks are masters of aerial assault and rapid-strike combined arms warfare.',
 chapter:'Storm Hawks',seg:'Segmentum Obscurus'},
{id:'talus',name:'Talus IV (Ruins)',x:363,y:272,type:'ruins',founding:'later',
 info:'Ruined former chapter world of the Brazen Claws. Talus IV was reduced to rubble by sustained Chaos assault. The Brazen Claws, severely depleted, continue fighting from a secondary base.',
 chapter:'Brazen Claws',seg:'Segmentum Obscurus'},
{id:'fortress_cp',name:'Fortress',x:470,y:210,type:'fortress',founding:'later',
 info:'Chapter world of the Crimson Paladins. A heavily fortified star system noted for its cascading layers of orbital defenses and subterranean ground fortifications.',
 chapter:'Crimson Paladins',seg:'Segmentum Obscurus'},
{id:'varsavia',name:'Varsavia',x:525,y:222,type:'civilized',founding:'later',
 info:'Chapter world of the Silver Skulls. The Silver Skulls are known for their reverence of augury and divination — they consult their Prognosticators before every battle engagement.',
 chapter:'Silver Skulls',seg:'Segmentum Obscurus'},
 
// Ultima Segmentum
{id:'preyspire',name:'Preyspire',x:572,y:278,type:'civilized',founding:'later',
 info:'Chapter world of the Hawks. A high-gravity world of soaring rock formations that produces warriors of exceptional strength, speed, and aggressive predatory instinct.',
 chapter:'Hawks',seg:'Ultima Segmentum'},
{id:'bellicas',name:'Bellicas',x:617,y:337,type:'civilized',founding:'later',
 info:'Chapter world of the Emperor\'s Swords. Devoted crusaders who take the Emperor\'s Word as absolute mandate. Bellicas is a world of deep-rooted knightly culture and chivalric tradition.',
 chapter:"Emperor's Swords",seg:'Ultima Segmentum'},
{id:'honourum',name:'Honourum',x:723,y:222,type:'civilized',founding:'later',
 info:'Chapter world of the Novamarines. Direct successors of the Ultramarines, the Novamarines exemplify the Codex Astartes in all their operations throughout Ultima Segmentum.',
 chapter:'Novamarines',seg:'Ultima Segmentum'},
{id:'vori',name:'Vori-Secundus',x:795,y:262,type:'ruins',founding:'later',
 info:'Abandoned former chapter world of the Crimson Castellans. Vori-Secundus was stripped of all life by a Tyranid splinter fleet. The Crimson Castellans seek vengeance and reclamation.',
 chapter:'Crimson Castellans',seg:'Ultima Segmentum'},
{id:'jonol',name:'Jonol',x:845,y:312,type:'civilized',founding:'later',
 info:'Chapter world of the Honoured Sons. Remote and fiercely independent, the Honoured Sons guard the approaches to the Eastern Fringe with unwavering, grim resolve.',
 chapter:'Honoured Sons',seg:'Ultima Segmentum'},
{id:'prism',name:'Prism',x:688,y:368,type:'desolate',founding:'later',
 info:'SYSTEM DESIGNATION: PRISM — ALL RECORDS DELETED. Access restricted to Inquisition authorization ALPHA BLACK. Chapter status: UNKNOWN. All inquiry routed to Ordo Malleus.',
 chapter:'[CLASSIFIED]',seg:'Ultima Segmentum'},
{id:'firestorm',name:'Firestorm',x:670,y:398,type:'volcanic',founding:'later',
 info:'Chapter world of the Aurora Chapter. A volcanic world of constant eruptions and lava seas. The Aurora Chapter\'s warriors bear flame-bright armor and strike with the violence of their homeworld.',
 chapter:'Aurora Chapter',seg:'Ultima Segmentum'},
{id:'armato',name:'Armato',x:690,y:428,type:'fortress',founding:'later',
 info:'Chapter world of the Sons of Orar. The Sons of Orar follow the example of the legendary Ultramarines captain Orar, pursuing excellence and honor in every military endeavor.',
 chapter:'Sons of Orar',seg:'Ultima Segmentum'},
{id:'obsidia',name:'Obsidia',x:706,y:452,type:'desolate',founding:'later',
 info:'Chapter world of the Sable Swords. A dark world of volcanic obsidian glass. The Sable Swords are as sharp and unforgiving as the obsidian plains they have called home for centuries.',
 chapter:'Sable Swords',seg:'Ultima Segmentum'},
{id:'orpheus',name:'Orpheus Prime',x:695,y:488,type:'civilized',founding:'later',
 info:'Chapter world of the Praetors of Orpheus. Positioned near the Eastern Fringe, the Praetors stand as the last bulwark of organized Imperial resistance against threats from beyond the galaxy\'s edge.',
 chapter:'Praetors of Orpheus',seg:'Ultima Segmentum'},
{id:'icefang',name:'Icefang',x:620,y:452,type:'ice',founding:'later',
 info:'Chapter world of the Tigers Argent. Located near the Maelstrom warp storm, Icefang\'s warriors battle on two fronts: the frozen wastelands of their homeworld, and the endless Chaos raiders from the rift.',
 chapter:'Tigers Argent',seg:'Ultima Segmentum'},
{id:'erenon',name:'Erenon',x:595,y:495,type:'civilized',founding:'later',
 info:'Chapter world of the Celestial Guard. The Celestial Guard maintains watchful vigil over the space lanes near the Maelstrom, interdicting Chaos pirates and raiding warbands.',
 chapter:'Celestial Guard',seg:'Ultima Segmentum'},
{id:'mancora',name:'Mancora',x:640,y:518,type:'civilized',founding:'later',
 info:'Chapter world of the Howling Griffons. Noted for their brilliant quartered livery of red and yellow, the Howling Griffons are a beacon of Imperial glory in the darkness of Ultima Segmentum.',
 chapter:'Howling Griffons',seg:'Ultima Segmentum'},
{id:'oxatan',name:'Oxatan',x:585,y:532,type:'desolate',founding:'later',
 info:'Chapter world of the Red Legion. A dry, mineral-rich world. The Red Legion are known for their aggressive, overwhelming assault tactics that leave nothing but ruin in their wake.',
 chapter:'Red Legion',seg:'Ultima Segmentum'},
{id:'talon',name:'Talon (Abandoned)',x:593,y:572,type:'ruins',founding:'later',
 info:'Abandoned former chapter world of the Storm Falcons. Talon was forsaken after catastrophic daemonic incursion. The Storm Falcons relocated to a mobile fortress-monastery platform.',
 chapter:'Storm Falcons',seg:'Ultima Segmentum'},
{id:'newfound',name:'Newfound',x:690,y:548,type:'civilized',founding:'later',
 info:'Chapter world of the Genesis Chapter. Direct successors of the Ultramarines, the Genesis Chapter strictly adheres to the Codex Astartes. Their world is a bastion of order.',
 chapter:'Genesis Chapter',seg:'Ultima Segmentum'},
{id:'macragge',name:'Macragge',x:700,y:562,type:'civilized',founding:'first',
 info:'Homeworld of the Ultramarines Chapter. Macragge is one of the most developed worlds in Ultima Segmentum — a shining example of Imperial civilization. The Fortress of Hera is their legendary fortress-monastery.',
 chapter:'Ultramarines',seg:'Ultima Segmentum'},
{id:'nihilas',name:'Nihilas',x:630,y:597,type:'desolate',founding:'later',
 info:'Chapter world of Death Strike. A desolate world near the galactic south. The Death Strike Chapter specializes in precision strikes against high-value targets, often acting under direct Inquisitorial mandate.',
 chapter:'Death Strike',seg:'Ultima Segmentum'},
{id:'munduspyra',name:'Mundus Pyra',x:645,y:628,type:'volcanic',founding:'later',
 info:'Chapter world of the Fire Lords. A world of perpetual firestorms and burning plains. The Fire Lords honor the legacy of their progenitors the Salamanders, wielding flame as both weapon and purifier of heresy.',
 chapter:'Fire Lords',seg:'Ultima Segmentum'},
{id:'necris',name:'Necris',x:525,y:657,type:'desolate',founding:'later',
 info:'Chapter world of the Marines Exemplar. A stark, harsh world that breeds warriors of exceptional character. The Marines Exemplar serve as living embodiments of the Codex Astartes in every action.',
 chapter:'Marines Exemplar',seg:'Ultima Segmentum'},
{id:'maelstrom',name:'The Maelstrom',x:522,y:422,type:'warpstorm',founding:'special',
 info:'A massive permanent Warp rift in the heart of Ultima Segmentum. The Maelstrom is a breach in realspace home to countless Chaos warbands, renegades, and daemonic entities. Smaller than the Eye of Terror, yet no less terrible.',
 chapter:'Chaos Domain',seg:'Ultima Segmentum'},
 
// Eastern Fringe
{id:'sternac',name:'Sternac',x:835,y:508,type:'desolate',founding:'later',
 info:'Chapter world of the Iron Lords. On the very edge of the Eastern Fringe, Sternac is a world of iron plains and perpetual storms. The Iron Lords stand ready against the encroaching Tyranid Hive Fleets.',
 chapter:'Iron Lords',seg:'Eastern Fringe'},
{id:'repentance',name:'Repentance',x:870,y:578,type:'artificial',founding:'later',
 info:'Artificial world and chapter home of The Nameless. Little is recorded of this enigmatic chapter or their constructed habitat. Contact has been sporadic at best. Their purpose remains classified.',
 chapter:'The Nameless',seg:'Eastern Fringe'},
{id:'omega_m',name:'Omega Marines',x:848,y:528,type:'civilized',founding:'later',
 info:'Chapter world of the Omega Marines. Their symbol — the Omega — represents both the End and eternal vigilance before it. The Omega Marines are specialists in defensive warfare and last-stand engagements.',
 chapter:'Omega Marines',seg:'Eastern Fringe'},
{id:'coralax',name:'Coralax',x:855,y:388,type:'civilized',founding:'later',
 info:'Chapter world of the Knights of the Raven. Successors of the Raven Guard, the Knights of the Raven maintain the stealth and sudden-strike tactics of their progenitor Corax.',
 chapter:'Knights of the Raven',seg:'Ultima Segmentum'},
{id:'erwynn',name:"Erwynn's World",x:820,y:438,type:'ruins',founding:'later',
 info:'Former chapter world of the Dragon Lords — Contact Lost. An Inquisitorial task force dispatched to investigate has not reported back. The Dragon Lords are presumed destroyed or corrupted.',
 chapter:'Dragon Lords (Lost)',seg:'Eastern Fringe'},
 
// Pelegron Cluster / Ghoul Stars
{id:'iron_cr',name:'Iron Crusaders',x:692,y:170,type:'crusade',founding:'later',
 info:'The Iron Crusaders are engaged in a long-form Crusade through the Pelegron Cluster, combating Ork warbands and Chaos incursions. Their crusade fleet has been active for over 300 years.',
 chapter:'Iron Crusaders',seg:'Pelegron Cluster'},
{id:'occludus',name:'Occludus',x:845,y:138,type:'desolate',founding:'later',
 info:'Chapter world of the Death Spectres. Located in the dreaded Ghoul Stars, the Death Spectres are one of the most mysterious and feared chapters in the Imperium. Their homeworld radiates an aura of cold ancient dread.',
 chapter:'Death Spectres',seg:'Ghoul Stars'},
{id:'elusia',name:'Elusia Prime',x:750,y:183,type:'artificial',founding:'later',
 info:'Artificial world and chapter home of the Doom Legion. Elusia Prime is a vast orbital construct in the outer reaches, from which the Doom Legion projects Imperial power across the Ghoul Stars region.',
 chapter:'Doom Legion',seg:'Ghoul Stars'},
{id:'blkt2',name:'Black Templars',x:685,y:162,type:'crusade',founding:'second',
 info:'A Black Templars Crusade fleet operating near the Pelegron Cluster. The Black Templars maintain numerous simultaneous Crusades across the entire galaxy, answering the Emperor\'s call for eternal holy war.',
 chapter:'Black Templars',seg:'Segmentum Obscurus'},
 
// Segmentum Tempestus
{id:'raikan',name:'Raikan',x:190,y:568,type:'civilized',founding:'later',
 info:'Chapter world of the Red Talons. A world in the deep galactic south, the Red Talons are an exceptionally secretive chapter known for their extreme methods of purging all traces of Chaos taint.',
 chapter:'Red Talons',seg:'Segmentum Tempestus'},
{id:'phobian',name:'Phobian',x:240,y:597,type:'desolate',founding:'later',
 info:'Chapter world of the Dark Hunters. The Dark Hunters are expert hunters of Chaos cultists and daemonic entities, using patient, methodical pursuit tactics to run their quarry to ground.',
 chapter:'Dark Hunters',seg:'Segmentum Tempestus'},
{id:'deliverance',name:'Deliverance',x:210,y:618,type:'desolate',founding:'first',
 info:'Homeworld of the Raven Guard Chapter. Once a world of enslaved laborers, Deliverance was freed by Primarch Corvus Corax. The Raven Guard specialize in guerrilla warfare, stealth, and sudden devastating strikes from shadow.',
 chapter:'Raven Guard',seg:'Segmentum Tempestus'},
{id:'rynnsworld',name:"Rynn's World",x:350,y:618,type:'civilized',founding:'second',
 info:"Homeworld of the Crimson Fists Chapter, successors of the Imperial Fists. Rynn's World was devastated when the chapter's missile silos detonated accidentally. The Crimson Fists survived and rebuilt — a symbol of Imperial resilience.",
 chapter:'Crimson Fists',seg:'Segmentum Tempestus'},
{id:'gryphonne',name:'Knights of Gryphonne',x:335,y:668,type:'civilized',founding:'later',
 info:'Chapter world of the Knights of Gryphonne. Situated deep in the galactic south, the Knights of Gryphonne guard against unknown threats from the galactic periphery and the Veiled Region.',
 chapter:'Knights of Gryphonne',seg:'Segmentum Tempestus'},
];



const CONNECTIONS=[
 ['terra','therock',0.15],
 ['terra','macragge',0.12],
 ['fenris','baal',0.1],
 ['deliverance','macragge',0.1],
 ['macragge','sternac',0.08],
 ['nocturne','munduspyra',0.1],
 ['terra','rynnsworld',0.1],
 ['orpheus','jonol',0.1],
 ['iron_cr','blkt2',0.1],
 ['macragge','honourum',0.08],
];


const bgCanvas=document.getElementById('bgCanvas');
const mapCanvas=document.getElementById('mapCanvas');
const scanLines=document.getElementById('scanLines');

const gl=bgCanvas.getContext('webgl');
const ctx=mapCanvas.getContext('2d');


